### ISSUE TITLE
Non-interactive backend for matplotlib

### ISSUE THREAD

**Issue by thperret** [pyhrf/pyhrf#104]
There is a issue related to `$DISPLAY` environment variable with matplotlib when running the tests from a non graphical terminal (e.g. from ssh or on the cluster).
On travis the issue is bypassed by using a `matplotlibrc` file setting the backend to `Agg` but IMHO, it should run without external fixes.

**Comment by thomas-vincent** [comment]
I ran into this issue of non-interactivity and tried to set it on-the-fly
but could not make it work ... thus the external file. Acutally, as far as
I remember, using on-the-fly setting of the backend didn't seem to work on
travis, but it worked locally on my machine.

**Comment by thperret** [comment]
Oh OK.
Actually, I tried (and succeeded) to fix it on my machine (you can check the hacks I used on these commits: 5360bc7edcb5661fe9220ba3a3cb135d2fe5a1ec, d0d97d721869b42f46f0a7358ed3619bf7a7a28b and ee6067fd7ac4842293bbc5266f2d79b2aeefb88e).
I'm currently trying to make it work on travis. It's mainly to make it work easily on the cluster.

**Comment by thperret** [comment]
The [travis-ci tests just passed](https://travis-ci.org/thperret/pyhrf/builds/54736416) with the fixes I applied so I think I'll use that (once I cleaned up everything) and make a PR.
