### ISSUE TITLE
covariance matrix

### ISSUE THREAD

**Issue by ainafp** [pyhrf/pyhrf#117]
covariance matrix with different D matrices to take into account different levels of smoothness depending on the part of the HRF

**Comment by thperret** [comment]
I implemented it in the `pyhrf.vbjde.vem_tools.buildFiniteDiffMatrix` function on a branch on my local repo. I'm still testing it and I didn't yet pushed it on my remote repo.

**Comment by salma1601** [comment]
ok, I'll give it a look once tested and pushed.
@ainafp May be in the future this covariance matrix can be inferred from the data, so that the time to undershoot is not enforced ?

**Comment by thperret** [comment]
@salma1601 Yes I strongly agree with that!
