### ISSUE TITLE
Rewrite the pyhrf_maketests

### ISSUE THREAD

**Issue by thperret** [pyhrf/pyhrf#88]
Add possibility to run only one test, group of tests, profiling, using nose, using unittest, w/ or w/o doctests...

**Comment by thomas-vincent** [comment]
pyhrf_maketest already allows to run only one test:

pyhrf_maketest testmodule.TestCase.test_func

Maybe we could directly use nose and get rid of this in-house command?

**Comment by thperret** [comment]
Indeed, now I remember you already told me about this possibility to run only one test.

Concerning the script I think it could be usefull to keep it and allow to choose from the module we want to use and furthermore the possibility to make some profiling (I just happen to need to use some profiling).

Some ideas:
`pyhrf_maketests --module unittest --doctest --profile testmodule.TestCase.test_func`

**Comment by thperret** [comment]
Eventually, I agree with @thomas-vincent, lets's only use nose command line and get rid of this command
