### ISSUE TITLE
xndarray.get_domain doctest fails

### ISSUE THREAD

**Issue by thperret** [pyhrf/pyhrf#89]
using `nosetests --with-doctest -v pyhrf.ndarray:xndarray.get_domain`, I get :
```bash
Doctest: pyhrf.ndarray.get_domain ... FAIL

======================================================================
FAIL: Doctest: pyhrf.ndarray.get_domain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for get_domain
  File "/home/tperret/code/pyhrf/python/pyhrf/ndarray.py", line 195, in get_domain

----------------------------------------------------------------------
File "/home/tperret/code/pyhrf/python/pyhrf/ndarray.py", line 202, in get_domain
Failed example:
    c.get_domain('y')
Expected:
    array(['plop', 'plip'],
          dtype='|S4')
Got:
    array(['plop', 'plip'], 
          dtype='|S4')


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
```
but the `Expected` and `Got` sections look identical.
In fact every doctests with numpy array and `dtype` argument seems to fail. (check `nosetests --with-doctest -v pyhrf.ndarray` command)

**Comment by thperret** [comment]
@thomas-vincent : I'm assigning you to this because I think you will have more success than I had, I spend some time on it without any success

**Comment by thomas-vincent** [comment]
Ok, I'm on it today!

**Comment by thperret** [comment]
While reading the doctest documentation (for something else), I came accross the [`NORMALIZE_WHITESPACE`](https://docs.python.org/2/library/doctest.html?highlight=blankline#doctest.NORMALIZE_WHITESPACE) option. So I tested it on the failing doctest and it's passing (just add `# doctest: +NORMALIZE_WHITESPACE` on the doctest line).
@thomas-vincent do you want me to correct it ?

**Comment by thomas-vincent** [comment]
I did a pull request.
Weird, the issue number is not associated though I specify it: "[#89]" at
the beginning of the commit message. Maybe it should go at the end?
